// components/ui/Footer.vue
<template>
  <footer
    class="bg-[#171717] text-center border-t-gray-light border-t-solid border-t-1 mt-8"
  >
    <div class="mx-auto px-4 py-5">
      <div class="grid grid-cols-3 gap-4 items-center align-center">
        <!-- Email -->
        <div>
          <a href="mailto:brian.edison.nguyen@gmail.com"
            >brian.edison.nguyen@gmail.com</a
          >
        </div>
        <!-- Brand -->
        <div>
          <img
            src="https://res.cloudinary.com/buraiyen/image/upload/c_scale,w_110/v1662578878/BEN_Website/BEN-logo-navbar.webp"
            width="150px"
            height="100px"
            class="w-150px h-100px"
            loading="lazy"
            alt="BEN Logo"
          />
        </div>
        <!-- Icons -->
        <div class="flex">
          <a href="https://www.linkedin.com/in/brian-e-nguyen/" target="_blank">
            <div class="i-bxl-linkedin-square text-5xl mx-2" />
          </a>
          <a href="https://github.com/Buraiyen/" target="_blank">
            <div class="i-bxl-github text-5xl mx-2" />
          </a>
          <a href="https://www.instagram.com/buraiyen_" target="_blank">
            <div class="i-bxl-instagram text-5xl mx-2" />
          </a>
        </div>
      </div>
      <div class="border-t-gray-light border-t-solid border-t-1 text-gray">
        <p>
          <a
            href="https://creativecommons.org/licenses/by-nc-sa/4.0/"
            target="_blank"
            >CC BY-NC-SA 4.0</a
          >
          2023-PRESENT &copy; Brian Nguyen
        </p>
        <p>
          See an issue?
          <a href="https://github.com/Buraiyen/brianenguyen.com/pulls"
            >Submit a pull request!</a
          >
        </p>
      </div>
    </div>
  </footer>
</template>

// src/components/ui/footer/Footer.jsx
import React from 'react';
import { Container, Grid } from '@mui/material';
import { Link } from 'react-router-dom';
import './Footer.css';
import FooterBrand from './FooterBrand';
import FooterButtons from './FooterButtons';

const Footer = () => {
  return (
    <footer className='footer'>
      <Container maxWidth='xl'>
        <div className='footer__block'>
          <Grid container spacing={3}>
            <Grid item xs={12} md={4}>
              <div className='footer__section'>
                <a
                  href='mailto:brian.edison.nguyen@gmail.com'
                  className='footer__link'
                >
                  brian.edison.nguyen@gmail.com
                </a>
              </div>
            </Grid>{' '}
            <Grid item xs={12} md={4}>
              <FooterBrand />
            </Grid>{' '}
            <Grid item xs={12} md={4}>
              <div className='footer__section'>
                <FooterButtons />
              </div>
            </Grid>
          </Grid>
        </div>
      </Container>
      <hr className='footer__line-divider' />
      <Container maxWidth='xs'>
        <p className='footer__text'>
          <a
            href='https://creativecommons.org/licenses/by-nc-sa/4.0/'
            target='_blank'
          >
            CC BY-NC-SA 4.0
          </a>{' '}
          {new Date().getFullYear()}-PRESENT &copy; Brian Nguyen
        </p>
        <p className='footer__text'>
          See an issue?{' '}
          <a
            href='https://github.com/Buraiyen/BEN-Website-React'
            target='_blank'
            rel='noreferrer'
          >
            Submit a pull request!
          </a>
        </p>
        <Link to='/privacy-policy' className='footer__privacy-policy-link'>
          Privacy Policy
        </Link>
      </Container>
    </footer>
  );
};

export default Footer;
