// src/components/home/Passion.jsx
import React from 'react';
import { Grid, Container } from '@mui/material';
import { Link } from 'react-router-dom';
import Button from '../ui/button/Button';
import './Passion.css';
const Passion = () => {
  return (
    <div className='passion'>
      <Container>
        <Grid container spacing={2}>
          <Grid item sm={12} md={5}>
            <img
              src='https://res.cloudinary.com/buraiyen/image/upload/c_scale,w_450/v1675707556/BEN_Website/BEN_profile3.webp'
              width='450px'
              height='450px'
              loading='lazy'
              className='passion__image'
              alt='Profile shot of me, sitting on the stairway at the Getty Museum'
            />
          </Grid>
          <Grid item sm={12} md={7}>
            <div className='passion__text'>
              <h1>My passion is software development</h1>
              <p>
                I am a software developer with a focus on frontend / fullstack
                development with over 7 years of experience. I don't just write
                code, I create solutions and transform them into digital
                realities
              </p>
              <center>
                <Link to='/portfolio'>
                  <Button className='btn-standard'>View My Work</Button>
                </Link>
              </center>
            </div>
          </Grid>
        </Grid>
      </Container>
    </div>
  );
};

export default Passion;

// components/index/Passion.vue
<template>
  <section class="grid zero:grid-cols-1 md:grid-cols-2 gap-4 mb-32">
    <div>
      <img
        src="https://res.cloudinary.com/buraiyen/image/upload/c_scale,w_450/v1675707556/BEN_Website/BEN_profile3.webp"
        width="450px"
        height="450px"
        loading="lazy"
        className="rounded
                  w-[100%] min-w-[200px] max-w[400px]
                  h-auto max-h-[400px]"
        alt="Profile shot of me, sitting on the stairway at the Getty Museum"
      />
    </div>
    <div>
      <h2>My passion is web development</h2>
      <p>
        I am a web developer with a focus on frontend / fullstack development
        with over 7 years of experience. I don't just write code, I create
        solutions and transform them into digital realities
      </p>
      <button class="btn">View My Work</button>
    </div>
  </section>
</template>
