// components/about/Quote.vue
<template>
  <p
    class="zero:text-[9vw]
            xs:text-[5vw]
            sm:text-[2.5vw]"
  >
    A fulfilling life is not preoccupied with material objects, prestige, or
    power. It is a life that is filled with true friendships, sharing, and
    caring for each other.
  </p>
  <p class="text-center text-xl italic">&mdash; Dharma Master Cheng Yen</p>
</template>

// src/components/about/Quote.jsx
import React from 'react';
import './Quote.css';

const Quote = () => {
  return (
    <div className='quote'>
      <h1 className='quote__content'>
        A fulfilling life is not preoccupied with material objects, prestige, or
        power. It is a life that is filled with true friendships, sharing, and
        caring for each other.
      </h1>
      <p className='quote__author'>— Dharma Master Chen Yeng</p>
    </div>
  );
};

export default Quote;
