// src/components/ui/jumbotron/Jumbotron.jsx
import './Jumbotron.css';

const Jumbotron = (props) => {
  return (
    <div className='jumbotron'>
      <picture>
        <source srcSet={props.src || ''} media='(min-width: 600px)' />
        <img
          src={props.srcMobile || ''}
          lazy-src={props.srcMobile || ''}
          alt=''
          className={props.srcMobile && 'jumbotron__image'}
          decoding='async'
          rel='preload'
        />
      </picture>
      <div className='jumbotron__container'>
        <h1 className='jumbotron__title'>{props.title}</h1>
        <p className='jumbotron__description'>{props.description}</p>
      </div>
    </div>
  );
};

export default Jumbotron;

// components/ui/Jumbotron.vue
<template>
  <div class="text-center relative bg-black border-none">
    <picture>
      <source :srcset="src || ''" media="(min-width: 600px)" />
      <img
        :src="srcMobile || ''"
        :lazy-src="srcMobile || ''"
        alt=""
        decoding="async"
        class="object-cover w-screen relative z-0"
      />
    </picture>
    <div class="absolute top-[50%] left-[50%]">
      <h1 class="text-white">{{ jumbotronTitle }}</h1>
      <p class="text-white">{{ jumbotronDesc }}</p>
    </div>
  </div>
</template>

<script setup lang="ts">
defineProps<{
  src?: string
  srcMobile?: string
  jumbotronTitle?: string
  jumbotronDesc?: string
}>()
</script>
