// src/components/about/facts/Facts.jsx
import React from 'react';
import { Grid } from '@mui/material';
import './Facts.css';

const Facts = () => {
  return (
    <div className='facts'>
      <Grid container spacing={5}>
        <Grid item sm={12} md={4}>
          <center>
            <img
              src='https://res.cloudinary.com/buraiyen/image/upload/c_scale,w_600/v1642186572/BEN_Website/BEN_profile_night.webp'
              alt='Me smiling at the camera'
              className='facts__image'
              loading='lazy'
            />
          </center>
        </Grid>
        <Grid item sm={12} md={8}>
          <div className='facts__section'>
            <h2 className='header'>Things that define me</h2>
            <h3 className='subheader'>
              I am a software developer, photographer, drummer, gamer,
              pro-wrestling enjoyer, and Linkin Park listener
            </h3>
          </div>
        </Grid>
      </Grid>
    </div>
  );
};

export default Facts;

// components/about/Facts.vue
<template>
  <section class="grid zero:grid-cols-1 gap-4 md:grid-cols-2">
    <div>
      <img
        src="https://res.cloudinary.com/buraiyen/image/upload/c_scale,w_600/v1642186572/BEN_Website/BEN_profile_night.webp"
        alt="Me smiling at the camera"
        class="rounded-md w-[100%] max-w-[300px]"
        loading="lazy"
      />
    </div>
    <div>
      <h2>Things that define me</h2>
      <p>
        I am a web developer, photographer, drummer, gamer, pro-wrestling
        enjoyer, and Linkin Park listener
      </p>
    </div>
  </section>
</template>
